apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-gpu
  labels:
    name: ubuntu-gpu
spec:
  volumes:
  - name: site-data
    persistentVolumeClaim:
      claimName: pvc-nfs-mlo
  - hostPath:
      path: /usr/lib/nvidia-375/bin
    name: bin
  - hostPath:
      path: /usr/lib/nvidia-375
    name: lib
  containers:
  - name:  ubuntu-gpu
    image: nvidia/cuda
    command:
      - sleep
      - infinity
    resources:
      limits:
        alpha.kubernetes.io/nvidia-gpu: 1
    volumeMounts:
    - mountPath: /usr/local/nvidia/bin
      name: bin
    - mountPath: /usr/local/nvidia/lib
      name: lib
    - mountPath: /mlodata1
      name: site-data
      subPath: mysql
