apiVersion: v1
kind: ReplicationController
metadata:
  name: dmlb-worker
  labels:
    name: dmlb-worker
spec:
  replicas: 2
  selector:
    name: dmlb-worker
  template:
    metadata:
      labels:
        name: dmlb-worker
    spec:
      containers:
        - name: dmlb-worker
          image: ntxvm015.iccluster.epfl.ch/mlo/pytorch-mpi
          command:
            - sleep
            - infinity
          ports:
            - containerPort: 8888
              name: notebook
            - containerPort: 6006
              name: tensorboard
            - containerPort: 22
              name: ssh
          resources:
            limits:
              nvidia.com/gpu: 1
          env:
            - name: ROLE
              value: "worker"
          volumeMounts:
            - mountPath: /mlodata1
              name: mlodata
      volumes:
        - name: mlodata
          persistentVolumeClaim:
            claimName: mlo-scratch
