apiVersion: v1
kind: Pod
metadata:
  name: dmlb-master
  labels:
    name: dmlb-master
    role: master
spec:
  containers:
    - name:  dmlb-master
      image: ntxvm015.iccluster.epfl.ch/mlo/base
      command:
        - sleep
        - infinity
      ports:
        - containerPort: 8888
          name: notebook
        - containerPort: 6006
          name: tensorboard
        - containerPort: 22
          name: ssh
      env:
        - name: ROLE
          value: "master"
      resources:
        limits:
          nvidia.com/gpu: 1
      volumeMounts:
        - mountPath: /mlodata1
          name: mlodata
  volumes:
    - name: mlodata
      persistentVolumeClaim:
        claimName: mlo-scratch
---
apiVersion: v1
kind: Service
metadata:
  name: dmlb-master
  labels:
    name: dmlb-master
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      name: notebook
    - port: 6006
      name: tensorboard
    - port: 22
      name: ssh
  selector:
    name: dmlb-master
