kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          image: ntxvm015.iccluster.epfl.ch/icit-images/spark:2.2.0
          imagePullPolicy: Always
          command: ["/spark-master"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              cpu: 1
          volumeMounts:
          - mountPath: /icit
            name: icit
      volumes:
        - name: icit
          persistentVolumeClaim:
            claimName: ic-it-scratch
---
kind: Service
apiVersion: v1
metadata:
  name: spark-master
spec:
  ports:
    - port: 7077
      targetPort: 7077
      name: spark
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    component: spark-master
