apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spark-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: ntxvm015.iccluster.epfl.ch/icit-images/spark:2.2.0
          imagePullPolicy: Always
          command: ["/spark-worker"]
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 2
          volumeMounts:
          - mountPath: /icit
            name: icit
      volumes:
        - name: icit
          persistentVolumeClaim:
            claimName: ic-it-scratch
