version: '2'
services:
    base:
        build:
            context: .
            dockerfile: base/Dockerfile
        image:  itamtao/base
    tensorflow-cpu:
        build:
            context: .
            dockerfile: tensorflow/Dockerfile.cpu
        image:  itamtao/tensorflow:cpu
        depends_on:
          - base
    tensorflow-gpu:
        build:
            context: .
            dockerfile: tensorflow/Dockerfile.gpu
        image:  itamtao/tensorflow:gpu
        depends_on:
          - base
    torch:
        build:
            context: .
            dockerfile: torch/Dockerfile
        image:  itamtao/torch:gpu
        depends_on:
          - base
