version: '2'
services:
    mlo_ml:
        build:
            context: .
            dockerfile: Dockerfile
        image:  ntxvm015.iccluster.epfl.ch/mlo/ml:1.0
    mlo_ml_prod:
        build:
            context: .
            dockerfile: Dockerfile.prod
        image:  ntxvm015.iccluster.epfl.ch/mlo/ml_prod:1.0
