apiVersion: v1
kind: Pod
metadata:
  name: pod-ml
  labels:
    name: pod-ml
spec:
  volumes:
    - name: site-data
      persistentVolumeClaim:
        claimName: pvc-nfs-mlo
    - name: bin
      hostPath:
        path: /usr/lib/nvidia-375/bin
    - name: lib
      hostPath:
        path: /usr/lib/nvidia-375
    - name: libcuda-so
      hostPath:
        path: /usr/lib/x86_64-linux-gnu/libcuda.so
    - name: libcuda-so-1
      hostPath:
        path: /usr/lib/x86_64-linux-gnu/libcuda.so.1
    - name: libcuda-so-375-39
      hostPath:
        path: /usr/lib/x86_64-linux-gnu/libcuda.so.375.39
  containers:
    - name:  ml
      image: ntxvm015.iccluster.epfl.ch/mlo/ml:1.0
      imagePullPolicy: Always
      securityContext:
        privileged: true
        # runAsUser: 144057
        # fsGroup: 11169
      command:
        - sleep
        - infinity
      env:
        - name: LD_LIBRARY_PATH
          value: /usr/lib/nvidia
      ports:
        - containerPort: 8888
          name: notebook
        - containerPort: 6006
          name: tensorboard
      resources:
        limits:
          alpha.kubernetes.io/nvidia-gpu: 2
      volumeMounts:
        - mountPath: /usr/local/nvidia/bin
          name: bin
        - mountPath: /usr/lib/nvidia
          name: lib
        - mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so
          name: libcuda-so
        - mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
          name: libcuda-so-1
        - mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.375.39
          name: libcuda-so-375-39
        - mountPath: /mlodata1
          name: site-data
  imagePullSecrets:
  - name: icitkey
---
apiVersion: v1
kind: Service
metadata:
  name: svc-ml
  labels:
    name: svc-ml
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      name: notebook
    - port: 6006
      name: tensorboard
  selector:
    name: pod-ml
