apiVersion: v1
kind: Pod
metadata:
  name: ml
  labels:
    name: ml
spec:
  volumes:
  - name: site-data
    persistentVolumeClaim:
      claimName: pvc-nfs-mlo
  - hostPath:
      path: /usr/lib/nvidia-375/bin
    name: bin
  - hostPath:
      path: /usr/lib/nvidia-375
    name: lib
  containers:
  - name:  ml
    image: ntxvm015.iccluster.epfl.ch/mlo/ml:1.0
    ports:
      - containerPort: 8888
    command:
      - sleep
      - infinity
    resources:
      limits:
        alpha.kubernetes.io/nvidia-gpu: 1
    volumeMounts:
    - mountPath: /usr/local/nvidia/bin
      name: bin
    - mountPath: /usr/local/nvidia/lib
      name: lib
    - mountPath: /mlodata1
      name: site-data
