apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    name: test
spec:
  containers:
  - name:  test
    image: ic-registry.epfl.ch/mlo/test
    command:
      - sleep
      - infinity
    resources:
      limits:
        nvidia.com/gpu: 2 # requesting 2 GPUs
